package main

import "fmt"

func main() {

	fmt.Println(fmt.Sprintf("%0.f", 3.5))
	//str := ` im_sms_mo_info
	//im_tenant_info
	//im_push_template_apply
	//im_wechat_his_20180927
	//im_wechat_temp_20180927
	//ng_sms_priority_route_template
	//ng_sms_sp_priority
	//ng_sms_sp_priority_apply
	//ng_sms_sp_priority_apply_base
	//ng_sms_sp_statistics
	//ng_sms_template_apply_suggest
	//sys_nums
	//im_sms_sp_account_bak
	//ng_sms_signature_bak
	//ng_sms_template_signature_bak
	//ng_sms_channel_bak
	//ng_sms_belong_system_bak
	//ng_sms_channel_mapping
	//ng_sms_template_signature_apply
	//ng_sms_template_apply
	//ng_sms_channel_mapping_apply
	//ng_sms_template_sp_apply
	//ng_sms_template_apply_base
	//im_sms_his
	//im_sms_his_old
	//im_sms_info
	//im_sms_blacklist_opr_log
	//im_sms_his_arc
	//im_sms_his_report
	//im_sms_inner_template_sp
	//im_sms_in_out_template
	//im_sms_sp_available
	//im_sms_temp
	//im_cell_prefix
	//im_sms_sp_command
	//im_msg_channel_config
	//im_sms_send_account
	//im_sms_sp_base_code
	//im_push_jiguang_config
	//im_push_channel_app_config
	//ng_sms_temp
	//im_voice_sp_available
	//im_sms_not_exist_template
	//im_voice_report
	//im_flash_sms_temp
	//im_flash_sms_report
	//im_ivr_info
	//ng_sms_operation_log
	//push_notice_callback_jss
	//ng_sms_template_bak
	//ng_sms_template_sp_bak
	//ng_sms_sp_available_bak
	//ng_sms_department_bak
	//u_group_temp
	//im_wechat_his
	//push_notice
	//push_notice_callback
	//im_push_temp
	//ng_sms_info_20195_before
	//ng_sms_department
	//ng_sms_sp_available
	//ng_sms_template_sp
	//ng_sms_template
	//ng_sms_belong_system
	//ng_sms_channel
	//ng_sms_template_signature
	//ng_sms_signature
	//im_sms_sp_account
	//ng_sms_task_control
	//t_task_info
	//u_group
	//im_sms_report_his_20180830
	//im_chuanglan_voice_callback
	//im_mail_template
	//im_sms_blacklist
	//im_mail_his
	//im_msg_template
	//im_voice_his
	//push_notice_arc
	//t_task_his
	//busi_no_crtl
	//ng_sms_sp_report
	//u_group_info
	//im_wechat_template
	//im_wechat_temp
	//im_sms_report
	//im_ivr_call_back
	//ng_sms_info`
	//
	//strlist := strings.Split(str,"\n ")
	//fmt.Println(strings.Join(strlist,","))
}
